export { default as maleAvatar } from '../../resources/images/maleAvatar.png'
export { default as femaleAvatar } from '../../resources/images/femaleAvatar.png'
export { default as AmountGraph } from '../../resources/images/AmountGraph.png'
export { default as NumGraph } from '../../resources/images/NumGraph.png'
export { default as TimeGraph } from '../../resources/images/TimeGraph.png'
